- name: Kiosk upgrade and setup
  hosts: kiosks
  remote_user: root
  #strategy: mitogen_free
  strategy: free
  tasks:
    - name: Copy folder structure
      ansible.builtin.file:
        path: "/{{ item.path }}"
        state: directory
        recurse: yes
      with_community.general.filetree: "{{ playbook_dir }}/files-kiosk/"
      loop_control:
        label: "/{{ item.path }}"
      when: item.state == 'directory'
    - name: Copy and render template files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/{{ item.path | regex_replace('\\.jinja2$', '') }}"
      with_community.general.filetree: "{{ playbook_dir }}/files-kiosk/"
      loop_control:
        label: "/{{ item.path | regex_replace('\\.jinja2$', '') }}"
      when: item.state == 'file' and item.path is regex('\\.jinja2$')
    - name: Copy static files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/{{ item.path }}"
      with_community.general.filetree: "{{ playbook_dir }}/files-kiosk/"
      loop_control:
        label: "/{{ item.path }}"
      when: item.state == 'file' and item.path is not regex('\\.jinja2$')

    - name: Fix permissions for copied scripts
      ansible.builtin.shell: |
        chown chromium-kiosk:chromium-kiosk /var/lib/chromium-kiosk/chromium-kiosk-prehook.sh
        chmod 750 /var/lib/chromium-kiosk/chromium-kiosk-prehook.sh

    - name: Set timezone
      ansible.builtin.file:
        src: /usr/share/zoneinfo/Europe/Madrid
        path: /etc/localtime
        state: link

    - name: NTP is enabled
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: started
        enabled: yes

    # dpms is heavily bugged on hasspas, the screen won't turn back on until hard reset.
    - name: On schedule is set up
      when: movistar_home is not defined
      ansible.builtin.systemd:
        name: dpms@on.timer
        state: started
        enabled: yes
    - name: Off schedule is set up
      when: movistar_home is not defined
      ansible.builtin.systemd:
        name: dpms@off.timer
        state: started
        enabled: yes

    - name: Drop patch for MAC address duplication
      when: movistar_home is defined
      ansible.builtin.copy:
        dest: /etc/systemd/network/01-mac-change.link
        content: |
          # All Movistar Home units ship with the same MAC address.
          # This should not have any effect in other hardware even if present.
          [Match]
          PermanentMACAddress=00:e0:4c:b8:22:01

          [Link]
          MACAddress={{ '00:e0:4c' | community.general.random_mac(seed=inventory_hostname) }}

    - name: Core packages are installed
      community.general.pacman:
        update_cache: true
        state: present
        name: [
          # Kiosk
          chromium-kiosk,
          # Useful for sending keystrokes over ssh
          # DISPLAY=:0 xdotool getactivewindow type 'your text here'
          xdotool,
          # Required for iwd.
          openresolv,
          # Misc node administration tools.
          btop, htop, lsof, nano, pacman-contrib
          # zram
          zram-generator,
        ]

    - name: zram is enabled
      ansible.builtin.systemd:
        name: systemd-zram-setup@zram0.service
        state: started

    - name: Upgrade system
      register: upgraded
      community.general.pacman:
        upgrade: true

    - name: Clean package cache
      ansible.builtin.shell: paccache -rk3

    - name: Print upgraded packages
      when: |
        'packages' in upgraded
      ansible.builtin.debug:
        var: upgraded.packages

    - name: Reboot node
      ansible.builtin.reboot: {}
      when: |
        ('packages' in upgraded) and (upgraded.packages | intersect(['chromium-kiosk', 'qiosk', 'linux', 'linux-lts']) | length > 0)
