- name: Basic host setup
  hosts: workers
  remote_user: root
  strategy: free
  tasks:
  - name: Core packages are installed
    community.general.pacman:
      # https://unix.stackexchange.com/questions/274727/how-to-force-pacman-to-answer-yes-to-all-questions/584001#584001
      extra_args: --ask 4 --noconfirm
      state: present
      name: [
        cri-o, runc, kubernetes-tools, kubelet, nfs-utils,
        btop, htop, lsof
      ]

  - name: Override files are copied
    ansible.builtin.copy:
      src: files/
      dest: /

  - name: Systemd-resolved is disabled
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: false
      masked: true
  - name: CRI-O is started and enabled
    ansible.builtin.systemd:
      name: crio
      state: started
      enabled: yes

# Storage nodes need disks to be manually decrypted, so kubelet should not be enabled on them.
- name: Enable kubelet
  hosts: workers:!storage
  remote_user: root
  strategy: free
  tasks:
  - name: Kubelet is enabled
    ansible.builtin.systemd:
      name: kubelet
      enabled: yes

- name: Storage NFS setup
  hosts: storage
  remote_user: root
  strategy: free
  tasks:
    - name: Configure NFS exports
      ansible.builtin.copy:
        content: |
          # Legacy HASS mount
          /mnt/zmir/docker/homeassistant	10.0.0.0/26(rw,async,no_root_squash) 127.0.0.1(rw,async,no_root_squash)
          # NFS provisioner
          /mnt/zmir/k8s  10.0.0.0/26(rw,async,no_root_squash) 127.0.0.1(rw,async,no_root_squash)
          # Media
          /mnt/zmir/media  10.0.0.0/26(rw,async,no_root_squash) 127.0.0.1(rw,async,no_root_squash)
        dest: /etc/exports.d/kubernetes.exports
    - name: Enable NFS server
      ansible.builtin.systemd:
        name: nfs-server
        state: restarted
        # NFS unit has an overridden WantedBy on Terabox.
        enabled: yes
