- name: Upgrade control plane
  hosts: control_plane
  remote_user: root

  strategy: linear  # Required for ansible.builtin.pause
  serial: 1

  tasks:
    - name: Upgrade system
      register: upgraded
      community.general.pacman:
        upgrade: true
        update_cache: true
    - name: Print upgraded packages
      when: |
        'packages' in upgraded
      ansible.builtin.debug:
        var: upgraded.packages

    - name: Reboot node
      register: reboot
      when: |
        ('packages' in upgraded) and (upgraded.packages | intersect(['kubelet', 'cri-o', 'linux', 'linux-lts']) | length > 0)
      ansible.builtin.reboot:
    - name: Ensure control plane is up
      ansible.builtin.shell:
        cmd: kubectl get nodes
      register: getnodes
      until: getnodes is not failed
      retries: 6
      delay: 10
    - name: Wait for cluster to settle after CP reboot
      when: reboot is not skipped
      ansible.builtin.wait_for:
        timeout: 60
    - name: Plan upgrade
      register: plan
      ansible.builtin.shell:
        cmd: kubeadm upgrade plan -o json

    - meta: end_host
      when: plan.stdout_lines | length <= 1

    - name: Figure upgrade version if it was not provided
      # TODO: Be smarter than components[0].
      # Hack: We strip the first line as kubeadm outputs a non-json log line in there.
      ansible.builtin.set_fact:
        new_version: "{{ (plan.stdout_lines[1:] | join | from_json).components[0].newVersion }}"
      when: |
         new_version is not defined

    - name: Confirm upgrade
      ansible.builtin.pause:
        prompt: Confirm upgrade to {{ new_version }}

    - name: Apply upgrade
      register: apply
      ansible.builtin.shell:
        cmd: |
          kubeadm upgrade apply -y "{{ new_version }}"

    - name: Echo apply log
      ansible.builtin.debug:
        var: apply.stdout_lines

- name: Kubeadm upgrade nodes
  hosts: control_plane:workers
  remote_user: root
  tasks:
    - name: Upgrade node
      ansible.builtin.shell:
        cmd: kubeadm upgrade node
