- name: Basic host setup
  hosts: kubernetes
  remote_user: root

  tasks:
  - name: Core packages are installed
    community.general.pacman:
      update_cache: true
      # https://unix.stackexchange.com/questions/274727/how-to-force-pacman-to-answer-yes-to-all-questions/584001#584001
      extra_args: --ask 4 --noconfirm
      state: present
      name:
        - cri-o
        - kubernetes-tools
        - kubelet
  - name: Override files are copied
    ansible.builtin.copy:
      src: files/
      dest: /
