apiVersion: v1
kind: Pod
metadata:
  name: kine
  namespace: kube-system
  labels:
    component: kine
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  containers:
    - name: kine-postgres
      image: docker.io/postgres:15-alpine3.17
      env:
        - name: POSTGRES_USER
          value: kubernetes
        - name: POSTGRES_DB
          value: kubernetes
        - name: POSTGRES_PASSWORD
          value: kubernetes
      args:
        - --listen_addresses="127.0.0.1"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        - mountPath: /var/run/postgresql/
          name: socket
      readinessProbe:
        failureThreshold: 1
        periodSeconds: 5
        exec:
          command:
            - sh
            - -c
            - pg_isready --username=$POSTGRES_USER --dbname=$POSTGRES_DB --timeout=1
    - name: kine-kine
      image: docker.io/rancher/kine:v0.10.0-amd64
      securityContext:
        runAsUser: 0  # kine needs to read certs in /etc/kubernetes/pki, which are root:root owned.
      args:
        - --listen-address=0.0.0.0:2379
        - --metrics-bind-address=127.0.0.1:8080
        - --endpoint=postgres://kubernetes:kubernetes@/kubernetes?host=/socket
        - --server-cert-file=/pki/server.crt
        - --server-key-file=/pki/server.key
      ports:
        - containerPort: 2379
          name: etcd
        - containerPort: 8080
          name: metrics
      volumeMounts:
        - mountPath: /pki
          name: etcd-pki
        - mountPath: /socket
          name: socket
  volumes:
    - name: socket
      # This could be an EmptyDir, but they have been proven unreliable for static pods.
      hostPath:
        path: /run/kine/postgresql/
        type: DirectoryOrCreate
    - name: postgres-data
      hostPath:
        path: /opt/kine/postgresql/data
        type: DirectoryOrCreate
    - name: etcd-pki
      hostPath:
        path: /etc/kubernetes/pki/etcd/
        type: Directory
